import { SubjectPlan, InterviewTopic, DSATopic } from '../types';

export const PRESET_SUBJECT_PLANS: SubjectPlan[] = [
  {
    id: 'preset-frontend-mastery',
    title: 'Frontend Engineering & React Mastery',
    category: 'Web Development',
    description: 'Comprehensive curriculum covering JavaScript internals, React 19 architecture, Next.js 16, and Web Performance (FreeCodeCamp & ChaiCode inspired).',
    colorTheme: '#1F3B99',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    topics: [
      {
        id: 'fe-topic-1',
        title: 'JavaScript Engine & Event Loop Internals',
        description: 'Understand execution context, call stack, microtask queue vs macrotask queue, hoisting, and closures.',
        difficulty: 'Intermediate',
        status: 'in_progress',
        resources: [
          { title: 'ChaiCode JS Series', url: 'https://youtube.com' },
          { title: 'FreeCodeCamp JS Data Structures', url: 'https://www.freecodecamp.org' },
        ],
        checklist: [
          { id: 'fe-1-1', title: 'Master Execution Context, Call Stack & Hoisting', completed: true },
          { id: 'fe-1-2', title: 'Understand Microtask Queue vs Macrotask Queue (Promises vs setTimeout)', completed: true },
          { id: 'fe-1-3', title: 'Implement Debounce and Throttle functions from scratch', completed: false },
          { id: 'fe-1-4', title: 'Deep dive into Closures & Lexical Environment scope chain', completed: false },
        ],
        notes: 'Debouncing is key for search inputs. Throttling is ideal for window resize & scroll events.',
      },
      {
        id: 'fe-topic-2',
        title: 'React 19 & Next.js 16 App Router Architecture',
        description: 'React Fiber reconciliation, Server Components (RSC), Server Actions, custom hooks, and state management.',
        difficulty: 'Advanced',
        status: 'todo',
        resources: [
          { title: 'Next.js 16 Docs', url: 'https://nextjs.org/docs' },
          { title: 'React 19 Release Notes', url: 'https://react.dev' },
        ],
        checklist: [
          { id: 'fe-2-1', title: 'Understand React Fiber Reconciliation & Double Buffering', completed: false },
          { id: 'fe-2-2', title: 'Build custom hooks (useDebounce, useLocalStorage, useFetch)', completed: false },
          { id: 'fe-2-3', title: 'Master Next.js Server Components (RSC) vs Client Components', completed: false },
          { id: 'fe-2-4', title: 'Implement Next.js Server Actions & Form State Mutations', completed: false },
        ],
        notes: 'Keep Client Components at the leaf nodes to optimize bundle size.',
      },
      {
        id: 'fe-topic-3',
        title: 'Web Performance & Core Web Vitals (LCP, INP, CLS)',
        description: 'Optimizing page load speed, rendering pipelines, dynamic imports, and bundle analysis.',
        difficulty: 'Advanced',
        status: 'todo',
        resources: [
          { title: 'web.dev Vitals Guide', url: 'https://web.dev/vitals/' },
        ],
        checklist: [
          { id: 'fe-3-1', title: 'Audit LCP (Largest Contentful Paint) & INP (Interaction to Next Paint)', completed: false },
          { id: 'fe-3-2', title: 'Implement Lazy Loading & Dynamic Imports (next/dynamic / React.lazy)', completed: false },
          { id: 'fe-3-3', title: 'Optimize font loading & layout stability to reduce CLS', completed: false },
        ],
        notes: 'Focus on INP replacing FID in modern Core Web Vitals.',
      },
    ],
  },
  {
    id: 'preset-backend-system-design',
    title: 'Backend Engineering & System Design',
    category: 'System Architecture',
    description: 'Node.js event-driven runtime, MongoDB/SQL schema optimization, Caching, and Scalable Microservices.',
    colorTheme: '#10B981',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    topics: [
      {
        id: 'be-topic-1',
        title: 'Node.js Runtime & Asynchronous I/O',
        description: 'Libuv thread pool, Non-blocking I/O, Event Emitters, Streams & Buffers.',
        difficulty: 'Intermediate',
        status: 'in_progress',
        resources: [
          { title: 'Node.js Official Guides', url: 'https://nodejs.org/en/docs/guides/' },
        ],
        checklist: [
          { id: 'be-1-1', title: 'Understand Libuv Thread Pool & Asynchronous Event Loop', completed: true },
          { id: 'be-1-2', title: 'Master Node.js Streams (Readable, Writable, Transform) for large file transfer', completed: false },
          { id: 'be-1-3', title: 'Implement Express/Fastify Middleware Pipeline with centralized error handling', completed: false },
        ],
        notes: 'Streams prevent memory bloat when transferring large payloads.',
      },
      {
        id: 'be-topic-2',
        title: 'Database Architecture & Query Optimization',
        description: 'MongoDB indexing, aggregation pipelines, SQL joins, transactions, and ACID properties.',
        difficulty: 'Intermediate',
        status: 'todo',
        resources: [
          { title: 'MongoDB University', url: 'https://learn.mongodb.com' },
          { title: 'GeeksforGeeks DBMS Guide', url: 'https://www.geeksforgeeks.org/dbms/' },
        ],
        checklist: [
          { id: 'be-2-1', title: 'Design Compound Indexes & Compound Unique Constraints', completed: false },
          { id: 'be-2-2', title: 'Master MongoDB Aggregation Framework ($match, $group, $lookup)', completed: false },
          { id: 'be-2-3', title: 'Understand Database Transactions & ACID properties', completed: false },
        ],
        notes: 'Use explain() to inspect query execution plans and index utilization.',
      },
      {
        id: 'be-topic-3',
        title: 'System Design & High Availability',
        description: 'Load balancing, Redis caching, Rate Limiting, Message Queues (Kafka/RabbitMQ), and Microservices.',
        difficulty: 'Advanced',
        status: 'todo',
        resources: [
          { title: 'System Design Primer', url: 'https://github.com/donnemartin/system-design-primer' },
        ],
        checklist: [
          { id: 'be-3-1', title: 'Design Rate Limiter (Token Bucket / Leaky Bucket Algorithms)', completed: false },
          { id: 'be-3-2', title: 'Implement Redis Caching Strategy (Cache-Aside, Write-Through)', completed: false },
          { id: 'be-3-3', title: 'Understand Database Sharding & Consistent Hashing', completed: false },
        ],
        notes: 'Cache-Aside is the default pattern for most web microservices.',
      },
    ],
  },
  {
    id: 'preset-cs-fundamentals',
    title: 'Computer Science Fundamentals Core',
    category: 'CS Core',
    description: 'Essential theoretical foundations: Operating Systems, Computer Networks, and Database Management (GFG inspired).',
    colorTheme: '#8B5CF6',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    topics: [
      {
        id: 'cs-topic-1',
        title: 'Operating Systems (OS)',
        description: 'Processes vs Threads, CPU Scheduling, Deadlocks, Virtual Memory & Paging.',
        difficulty: 'Intermediate',
        status: 'todo',
        resources: [
          { title: 'GeeksforGeeks OS Track', url: 'https://www.geeksforgeeks.org/operating-systems/' },
        ],
        checklist: [
          { id: 'cs-1-1', title: 'Process vs Thread execution models & Inter-Process Communication (IPC)', completed: false },
          { id: 'cs-1-2', title: 'CPU Scheduling Algorithms (Round Robin, FCFS, SJF, Priority)', completed: false },
          { id: 'cs-1-3', title: 'Deadlock Conditions (Coffman conditions) & Banker’s Algorithm', completed: false },
          { id: 'cs-1-4', title: 'Virtual Memory, Page Faults & LRU Page Replacement', completed: false },
        ],
        notes: 'Deadlock requires 4 conditions: Mutual Exclusion, Hold & Wait, No Preemption, Circular Wait.',
      },
      {
        id: 'cs-topic-2',
        title: 'Computer Networks (CN)',
        description: 'TCP/IP Layered model, HTTP/HTTPS handshake, DNS lookup, and WebSockets vs Server-Sent Events.',
        difficulty: 'Intermediate',
        status: 'todo',
        resources: [
          { title: 'GeeksforGeeks Computer Networks', url: 'https://www.geeksforgeeks.org/computer-network-tutorials/' },
        ],
        checklist: [
          { id: 'cs-2-1', title: 'Understand TCP 3-Way Handshake & 4-Way Teardown', completed: false },
          { id: 'cs-2-2', title: 'TLS/SSL Certificate Handshake & Asymmetric/Symmetric Encryption', completed: false },
          { id: 'cs-2-3', title: 'DNS Resolution Process (Root DNS -> TLD -> Authoritative Nameserver)', completed: false },
          { id: 'cs-2-4', title: 'Compare HTTP/1.1 vs HTTP/2 (Multiplexing) vs HTTP/3 (QUIC)', completed: false },
        ],
        notes: 'HTTP/2 multiplexing removes head-of-line blocking at the application level.',
      },
    ],
  },
];

export const PRESET_INTERVIEW_TOPICS: InterviewTopic[] = [
  {
    id: 'int-react',
    category: 'React',
    progress: 75,
    notes: 'Focus on React 19 Fiber reconciliation, Server Components (RSC), custom hooks, and memoization.',
    resources: [
      { title: 'React 19 Official Docs', url: 'https://react.dev' },
      { title: 'FreeCodeCamp React Guide', url: 'https://freecodecamp.org' },
    ],
    checklist: [
      { id: 'int-r1', task: 'Explain Virtual DOM, Diffing Algorithm & Fiber Architecture', completed: true },
      { id: 'int-r2', task: 'Compare useState/useReducer vs Zustand/Redux for state management', completed: true },
      { id: 'int-r3', task: 'Explain useMemo, useCallback & React.memo optimization rules', completed: true },
      { id: 'int-r4', task: 'Demonstrate Server Components (RSC) vs Client Components in Next.js', completed: false },
    ],
  },
  {
    id: 'int-js',
    category: 'JavaScript',
    progress: 80,
    notes: 'Deep dive into Event Loop queues, Closures, Prototypal Inheritance, and async/await mechanics.',
    resources: [
      { title: 'ChaiCode JS Playlist', url: 'https://youtube.com' },
      { title: 'JS Info (javascript.info)', url: 'https://javascript.info' },
    ],
    checklist: [
      { id: 'int-js1', task: 'Master Call Stack, Event Loop, Microtask vs Macrotask queue', completed: true },
      { id: 'int-js2', task: 'Implement Polyfills for Array.map, filter, reduce, and Promise.all', completed: true },
      { id: 'int-js3', task: 'Explain Closures, Scope Chain & Memory Leak scenarios', completed: true },
      { id: 'int-js4', task: 'Implement Debounce & Throttle functions from scratch', completed: false },
    ],
  },
  {
    id: 'int-node',
    category: 'Node.js',
    progress: 60,
    notes: 'Event-driven Architecture, Libuv thread pool, Streams, Buffers, and Microservices.',
    resources: [
      { title: 'Node.js Guides', url: 'https://nodejs.org/en/docs/guides/' },
    ],
    checklist: [
      { id: 'int-n1', task: 'Explain Libuv Thread Pool & Asynchronous Non-blocking I/O model', completed: true },
      { id: 'int-n2', task: 'Master Streams (Readable, Writable, Transform) & Backpressure', completed: true },
      { id: 'int-n3', task: 'Implement Custom Express/Fastify Middleware Pipeline', completed: false },
      { id: 'int-n4', task: 'Build JWT & OAuth 2.0 Auth Flow with Refresh Tokens', completed: false },
    ],
  },
  {
    id: 'int-sysdesign',
    category: 'System Design',
    progress: 40,
    notes: 'Scalability, Load Balancers, Caching strategies (Redis), SQL vs NoSQL, and Rate Limiting.',
    resources: [
      { title: 'System Design Primer', url: 'https://github.com/donnemartin/system-design-primer' },
      { title: 'GeeksforGeeks System Design', url: 'https://geeksforgeeks.org' },
    ],
    checklist: [
      { id: 'int-sd1', task: 'Design URL Shortener (TinyURL) with Hash collision resolution', completed: true },
      { id: 'int-sd2', task: 'Design Rate Limiter (Token Bucket / Leaky Bucket algorithms)', completed: false },
      { id: 'int-sd3', task: 'Explain Redis Caching Strategies (Cache-Aside, Write-Through)', completed: false },
      { id: 'int-sd4', task: 'Design Real-Time Chat App with WebSockets & Redis Pub/Sub', completed: false },
    ],
  },
];

export const PRESET_DSA_TOPICS: DSATopic[] = [
  {
    id: 'dsa-arrays',
    name: 'Arrays & Hashing',
    category: 'Striver SDE / NeetCode 150',
    easySolved: 12,
    easyTotal: 15,
    mediumSolved: 18,
    mediumTotal: 25,
    hardSolved: 4,
    hardTotal: 10,
    notes: 'Focus on Two-Pointer patterns, Prefix Sums, and Hash Table lookup optimization.',
    lastRevised: new Date().toISOString().split('T')[0],
  },
  {
    id: 'dsa-twopointers',
    name: 'Two Pointers & Sliding Window',
    category: 'Striver SDE / NeetCode 150',
    easySolved: 8,
    easyTotal: 10,
    mediumSolved: 14,
    mediumTotal: 20,
    hardSolved: 3,
    hardTotal: 8,
    notes: 'Master fixed vs variable window size algorithms for substring problems.',
    lastRevised: new Date().toISOString().split('T')[0],
  },
  {
    id: 'dsa-trees',
    name: 'Binary Trees & BST',
    category: 'Striver SDE / NeetCode 150',
    easySolved: 10,
    easyTotal: 12,
    mediumSolved: 12,
    mediumTotal: 20,
    hardSolved: 5,
    hardTotal: 10,
    notes: 'Recursion depth, Inorder/Preorder/Postorder traversals, and Lowest Common Ancestor.',
    lastRevised: new Date().toISOString().split('T')[0],
  },
  {
    id: 'dsa-dp',
    name: 'Dynamic Programming (1D & 2D)',
    category: 'Striver SDE / NeetCode 150',
    easySolved: 6,
    easyTotal: 10,
    mediumSolved: 10,
    mediumTotal: 25,
    hardSolved: 2,
    hardTotal: 15,
    notes: 'Identify overlapping subproblems, memoization vs bottom-up tabulation.',
    lastRevised: new Date().toISOString().split('T')[0],
  },
  {
    id: 'dsa-graphs',
    name: 'Graphs & BFS/DFS',
    category: 'Striver SDE / NeetCode 150',
    easySolved: 4,
    easyTotal: 8,
    mediumSolved: 9,
    mediumTotal: 20,
    hardSolved: 3,
    hardTotal: 12,
    notes: 'Dijkstra algorithm, Topological Sort, Disjoint Set Union (DSU).',
    lastRevised: new Date().toISOString().split('T')[0],
  },
];
