import { JobApplication, InterviewTopic, DSATopic, SubjectPlan } from '../types';

export const SOFTWARE_ENGINEER_SEED_DATA: {
  subjectPlans: SubjectPlan[];
  dsaTopics: DSATopic[];
  interviewTopics: InterviewTopic[];
  jobs: JobApplication[];
} = {
  subjectPlans: [
    {
      id: 'subject-se-web-arch',
      title: 'Full-Stack Web Architecture & Performance',
      category: 'Web Development',
      description: 'Master modern frontend & backend architectures, Next.js App Router, SSR/SSG/ISR, V8 engine internals, and micro-frontend patterns.',
      colorTheme: '#1F3B99',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      topics: [
        {
          id: 'topic-react-fiber',
          title: 'React Concurrent Engine & Fiber Architecture',
          description: 'Deep dive into React Fiber reconciliation, work loop, priority scheduling, useTransition, and Server Components (RSC).',
          difficulty: 'Advanced',
          status: 'in_progress',
          resources: [
            { title: 'React Architecture Deep Dive', url: 'https://react.dev/reference/react' },
            { title: 'Understanding React Fiber', url: 'https://github.com/acdlite/react-fiber-architecture' },
          ],
          checklist: [
            { id: 'c1', title: 'Explain Fiber node structure & double buffering', completed: true },
            { id: 'c2', title: 'Implement custom useTransition hook for non-blocking UI', completed: true },
            { id: 'c3', title: 'Master Server vs Client Component boundary rules', completed: false },
            { id: 'c4', title: 'Debug memory leaks using Chrome Memory Profiler', completed: false },
          ],
          notes: 'Fiber splits reconciliation into incremental render units. Never perform heavy CPU work inside render phases.',
          lastRevised: new Date().toISOString().split('T')[0],
        },
        {
          id: 'topic-node-internals',
          title: 'Node.js Event Loop & Asynchronous I/O',
          description: 'Libuv thread pool architecture, event loop phases (Timers, Poll, Check), process.nextTick vs setImmediate, and worker threads.',
          difficulty: 'Intermediate',
          status: 'mastered',
          resources: [
            { title: 'Node.js Event Loop Guide', url: 'https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/' },
          ],
          checklist: [
            { id: 'c5', title: 'Understand 6 phases of Node.js event loop', completed: true },
            { id: 'c6', title: 'Handle stream backpressure & pipeline', completed: true },
            { id: 'c7', title: 'Benchmark Worker Threads for CPU intensive tasks', completed: true },
          ],
          notes: 'process.nextTick executes immediately after current operation completes, before next event loop phase!',
          lastRevised: new Date().toISOString().split('T')[0],
        },
      ],
    },
    {
      id: 'subject-se-sys-design',
      title: 'Distributed Systems & Microservices Design',
      category: 'System Architecture',
      description: 'Scalable system design patterns, distributed caching (Redis), message queues (Kafka), API gateways, and database sharding.',
      colorTheme: '#059669',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      topics: [
        {
          id: 'topic-[#1F3B99]-rate-limit',
          title: 'API Gateway & Rate Limiting Algorithms',
          description: 'Token Bucket, Leaky Bucket, Sliding Window Counter algorithms, Redis distributed locks, and Nginx reverse proxy tuning.',
          difficulty: 'Intermediate',
          status: 'in_progress',
          resources: [
            { title: 'System Design Primer', url: 'https://github.com/donnemartin/system-design-primer' },
          ],
          checklist: [
            { id: 'c8', title: 'Implement Sliding Window Rate Limiter in Redis', completed: true },
            { id: 'c9', title: 'Design API Gateway authentication middleware with JWT', completed: true },
            { id: 'c10', title: 'Configure Circuit Breaker pattern with Resilience4j/Hystrix', completed: false },
          ],
          notes: 'Sliding Window Log prevents traffic spikes at window boundaries compared to Fixed Window Counters.',
          lastRevised: new Date().toISOString().split('T')[0],
        },
      ],
    },
    {
      id: 'subject-se-db-eng',
      title: 'Database Engineering & Storage Engines',
      category: 'CS Core',
      description: 'Relational vs NoSQL trade-offs, B-Tree vs LSM-Tree indexes, transaction isolation levels, ACID guarantees, and sharding strategies.',
      colorTheme: '#D97706',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      topics: [
        {
          id: 'topic-db-indexing',
          title: 'SQL B-Tree Indexing & Query Execution Plans',
          description: 'Clustered vs Non-clustered indexes, composite index order, EXPLAIN ANALYZE execution trees, and connection pooling.',
          difficulty: 'Intermediate',
          status: 'mastered',
          resources: [
            { title: 'Use The Index, Luke!', url: 'https://use-the-index-luke.com/' },
          ],
          checklist: [
            { id: 'c11', title: 'Analyze EXPLAIN query plan for index scans vs seq scans', completed: true },
            { id: 'c12', title: 'Understand Composite Index Leftmost Prefix Rule', completed: true },
            { id: 'c13', title: 'Optimize slow queries using partial and expression indexes', completed: true },
          ],
          notes: 'Composite indexes must follow query WHERE filter order: Equality columns first, Range columns last!',
          lastRevised: new Date().toISOString().split('T')[0],
        },
      ],
    },
  ],

  dsaTopics: [
    {
      id: 'dsa-se-dp',
      name: 'Dynamic Programming (1D & 2D)',
      category: 'NeetCode 150 / Striver SDE',
      easySolved: 8,
      easyTotal: 10,
      mediumSolved: 16,
      mediumTotal: 20,
      hardSolved: 5,
      hardTotal: 10,
      notes: 'Master 0/1 Knapsack, Longest Common Subsequence (LCS), Edit Distance, and Matrix Chain Multiplication.',
      lastRevised: new Date().toISOString().split('T')[0],
    },
    {
      id: 'dsa-se-graphs',
      name: 'Graphs & Topological Sort',
      category: 'Striver SDE Sheet',
      easySolved: 6,
      easyTotal: 6,
      mediumSolved: 14,
      mediumTotal: 16,
      hardSolved: 6,
      hardTotal: 8,
      notes: 'Focus on Kahn Algorithm for Topo Sort, Dijkstra Shortest Path, Union-Find (Disjoint Set), and Cycle Detection.',
      lastRevised: new Date().toISOString().split('T')[0],
    },
    {
      id: 'dsa-se-trees',
      name: 'Binary Trees & BST',
      category: 'LeetCode 75',
      easySolved: 10,
      easyTotal: 10,
      mediumSolved: 15,
      mediumTotal: 15,
      hardSolved: 4,
      hardTotal: 5,
      notes: 'Lowest Common Ancestor (LCA), Tree Serialization/Deserialization, and Morris Inorder Traversal.',
      lastRevised: new Date().toISOString().split('T')[0],
    },
    {
      id: 'dsa-se-pointers',
      name: 'Two Pointers & Sliding Window',
      category: 'NeetCode 150',
      easySolved: 6,
      easyTotal: 6,
      mediumSolved: 10,
      mediumTotal: 10,
      hardSolved: 3,
      hardTotal: 3,
      notes: '100% Mastered! Trapping Rain Water, Minimum Window Substring, and 3Sum problems.',
      lastRevised: new Date().toISOString().split('T')[0],
    },
  ],

  interviewTopics: [
    {
      id: 'int-se-sysdesign',
      category: 'System Design & Distributed Systems' as any,
      progress: 75,
      notes: 'Focus on scalability trade-offs, CAP theorem, database partitioning, and caching strategies.',
      resources: [{ title: 'System Design Primer', url: 'https://github.com/donnemartin/system-design-primer' }],
      checklist: [
        { id: 'i1', task: 'Design a scalable URL Shortener (TinyURL) with KV storage & base62 encoding', completed: true },
        { id: 'i2', task: 'Design a Distributed Notification Service (Kafka + WebSockets + Push)', completed: true },
        { id: 'i3', task: 'Explain Consistent Hashing and Virtual Nodes for Database Sharding', completed: true },
        { id: 'i4', task: 'Design a Real-time Collaborative Document Editor (Operational Transformation / CRDTs)', completed: false },
      ],
    },
    {
      id: 'int-se-javascript',
      category: 'JavaScript & V8 Internals' as any,
      progress: 90,
      notes: 'Core JS runtime mechanics, prototype inheritance, event loop, closures, and garbage collection.',
      resources: [],
      checklist: [
        { id: 'i5', task: 'Explain V8 Engine hidden classes and inline caching', completed: true },
        { id: 'i6', task: 'Implement custom Polyfills for Promise.all, Promise.allSettled, and debounce', completed: true },
        { id: 'i7', task: 'Explain Event Delegation, Event Capturing, and Bubbling phases', completed: true },
        { id: 'i8', task: 'Identify and resolve Javascript memory leaks caused by detached DOM nodes', completed: false },
      ],
    },
    {
      id: 'int-se-backend',
      category: 'Backend & API Security' as any,
      progress: 80,
      notes: 'REST vs GraphQL vs gRPC, OAuth 2.0 PKCE flow, rate limiting, and SQL injection prevention.',
      resources: [],
      checklist: [
        { id: 'i9', task: 'Explain OAuth 2.0 Authorization Code Flow with PKCE for SPAs', completed: true },
        { id: 'i10', task: 'Design idempotent API endpoints using Idempotency Keys in headers', completed: true },
        { id: 'i11', task: 'Compare WebSockets, Server-Sent Events (SSE), and Long Polling', completed: true },
      ],
    },
  ],

  jobs: [
    {
      id: 'job-stripe',
      company: 'Stripe',
      role: 'Senior Full Stack Engineer',
      appliedDate: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
      status: 'Interview',
      salary: '$195,000 - $240,000 + Equity',
      location: 'Remote (US/Canada)',
      notes: 'System Design round scheduled for next Tuesday. Review API idempotency & distributed ledger patterns.',
    },
    {
      id: 'job-linear',
      company: 'Linear',
      role: 'Software Engineer - Infrastructure',
      appliedDate: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
      status: 'OA',
      salary: '$180,000 - $215,000',
      location: 'San Francisco / Remote',
      notes: 'Completed CodeSignal assessment (840 score). Await team match callback.',
    },
    {
      id: 'job-vercel',
      company: 'Vercel',
      role: 'Frontend Infrastructure Engineer',
      appliedDate: new Date(Date.now() - 18 * 86400000).toISOString().split('T')[0],
      status: 'Offer',
      salary: '$210,000 + $60k RSUs',
      location: 'Remote',
      notes: 'Written offer received! Negotiating equity vesting schedule.',
    },
    {
      id: 'job-google',
      company: 'Google',
      role: 'Software Engineer L4',
      appliedDate: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
      status: 'Applied',
      salary: '$190,000 - $230,000',
      location: 'Mountain View, CA',
      notes: 'Applied via employee referral from Alex.',
    },
  ],
};
